import type { Metadata } from "next";
import "./globals.css";
import { roboto } from "./fonts/fonts";
import { Analytics } from "@vercel/analytics/react"

export const metadata: Metadata = {
  title: "Ravenous App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        {children}
        <Analytics />
      </body>
    </html>
  );
}
